name: Autoapprove PRs

on:
  workflow_call:
    inputs:
      PR_URL:
        type: string
        required: true
    secrets:
      APPROVAL_TOKEN:
        required: true

permissions:
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.5.1
        with:
          github-token: "${{ secrets.APPROVAL_TOKEN }}"
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ inputs.PR_URL }}
          GITHUB_TOKEN: ${{ secrets.APPROVAL_TOKEN }}
  davidlday:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'davidlday' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ inputs.PR_URL }}
          GITHUB_TOKEN: ${{ secrets.APPROVAL_TOKEN }}
