name: Node.js CI

on:
  workflow_call:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  npm-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [lts/-1, lts/*, latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.5.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Clean Install
        run: npm ci
      - name: NPM Build
        run: npm run build --if-present
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Test Pack
        run: npm pack
