name: Node.js Test

on:
  workflow_call:

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  npm-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [lts/-1, lts/*, latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4.0.3
        with:
          node-version: ${{ matrix.node-version }}
      - name: NPM Clean Install
        run: npm ci
      - name: NPM Build
        run: npm run build --if-present
      - name: Test
        run: npm test
        env:
          CI: true
      - name: Test Pack
        run: npm pack
