name: Python Poetry MyPy Check

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        type: string
        required: false
        default: "3.x"
      src-path:
        description: "Source path for MyPy"
        type: string
        required: false
        default: "src/**/*.py"

jobs:
  python-mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: "poetry"
          python-version: "3.x"
      - name: Install project
        run: poetry install --with dev --no-interaction
      - name: MyPy
        run: |
          poetry run mypy ${{ inputs.src-path }} --config-file pyproject.toml
