name: Python Poetry CI

on:
  workflow_call:

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  lint:
    uses: prosegrinder/.github/.github/workflows/poetry-lint.yaml@main

  test:
    needs: lint
    uses: prosegrinder/.github/.github/workflows/poetry-test.yaml@main

  bump-dry-run:
    needs: test
    name: "Dry run Commitizen bump"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0
          submodules: true
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@0.15.1
        with:
          check_consistency: true
          dry_run: true
