name: Python Poetry Test

on:
  workflow_call:

# concurrency:
#   group: ci-${{ github.ref }}
#   cancel-in-progress: true

jobs:
  poetry-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          cache: "poetry"
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with dev --no-interaction --no-root
      - name: Install project
        run: poetry install --with dev --no-interaction
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/
