name: Python Test

on:
  workflow_call:

jobs:
  python-test:
    name: Python Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Install module
        run: |
          pip install -e .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
