name: Python Lint

on:
  workflow_call:

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          cache: "poetry"
          python-version: "3.x"
      - name: Install project
        run: poetry install --with dev --no-interaction
      - name: Black
        run: poetry run black . --check
      - name: Pylint
        run: poetry run pylint src/**/*.py
